FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/sdk:10.0-alpine as build-env
ARG DOMAIN_OWNER
ARG NUGET_REPO_NAME
ARG CODEARTIFACT_AUTH_TOKEN
ARG REGION

WORKDIR /AppCode

RUN cat > nuget.config <<EOF
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="${NUGET_REPO_NAME}" value="https://zeuslearning-${DOMAIN_OWNER}.d.codeartifact.${REGION}.amazonaws.com/nuget/${NUGET_REPO_NAME}/v3/index.json" />
  </packageSources>
</configuration>
EOF

COPY ./SubmissionProcessor.Worker/ ./SubmissionProcessor.Worker/
COPY ./TraineeManagementApi/ ./TraineeManagementApi/


WORKDIR /AppCode/SubmissionProcessor.Worker

RUN dotnet nuget update source ${NUGET_REPO_NAME} -u "aws" -p "${CODEARTIFACT_AUTH_TOKEN}" --store-password-in-clear-text --configfile /AppCode/nuget.config

RUN dotnet restore --configfile /AppCode/nuget.config

RUN rm -rf ./TraineeManagementApi/appsettings*.json
RUN rm -rf ./AppCode/TraineeManagementApi/appsettings*.json

RUN dotnet publish -c Release -o out --no-restore

# Uses runtime image instead of aspnet since it is a worker service
FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/aspnet:10.0-alpine as runtime
WORKDIR /App
COPY --from=build-env /AppCode/SubmissionProcessor.Worker/out .

# Fallback
COPY ./SubmissionProcessor.Worker/appsettings.example.json ./
RUN cp appsettings.example.json appsettings.json

ENTRYPOINT ["dotnet", "SubmissionProcessor.Worker.dll"]